### ISSUE TITLE
프로젝트 개발을 위한 정리 및 계획

### ISSUE THREAD

**Issue by yujiseok** [cheetah-is-laughing/quatre-foil#59]
## 작업 상세 내용
- [ ] 코드 리팩토링
- [ ] 마크업 정리

## 참고 사항

- 현재 개발이 어느 정도 진행되었는지 파악하기
- 개발 데드라인 정하기

**Comment by hyorimcho** [comment]
5월 1일 전까지 완료하는 것으로 하면 좋겠습니다!
